org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.parallel=false
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
kotlin.compiler.execution.strategy=in-process
android.aapt2.useDaemon=false
# aarch64 launch: aapt2 do Maven é x86_64 -> usar wrapper qemu: -Pandroid.aapt2FromMavenOverride=/root/tami-aapt2/aapt2
